src/Entity/Cliente.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\ClienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClienteRepository::class)
 */
class Cliente
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $nome;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $cpf_cnpj;

    /**
     * @ORM\Column(type="string", length=14, nullable=true)
     */
    private $telefone;

    public function __construct()
    {
        $this->getCompras = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNome(): ?string
    {
        return $this->nome;
    }

    public function setNome(string $nome): self
    {
        $this->nome = $nome;

        return $this;
    }

    public function getCpfCnpj(): ?string
    {
        return $this->cpf_cnpj;
    }

    public function setCpfCnpj(string $cpf_cnpj): self
    {
        $this->cpf_cnpj = $cpf_cnpj;

        return $this;
    }

    public function getTelefone(): ?string
    {
        return $this->telefone;
    }

    public function setTelefone(?string $telefone): self
    {
        $this->telefone = $telefone;

        return $this;
    }
}

src/Form/ClienteType.php
<?php

namespace App\Form;

use App\Entity\Cliente;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClienteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nome', TextType::class)
            ->add('cpf_cnpj', TextType::class)
            ->add('telefone', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cliente::class,
        ]);
    }
}

src/Controller/ClienteController.php
<?php

namespace App\Controller;

use App\Entity\Cliente;
use App\Form\ClienteType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ClienteController extends AbstractController
{
    /**
     * @Route("/cliente", name="cliente_index")
     */
    public function index(): Response
    {
        $clientes = $this->getDoctrine()->getRepository(Cliente::class)->findAll();

        return $this->render('cliente/index.html.twig', [
            'lista' => $clientes
        ]);
    }

    /**
     * @Route("/cliente/create", name="cliente_create")
     */
    public function create(Request $request): Response
    {
        $cliente = new Cliente();

        $form = $this->createForm(ClienteType::class, $cliente);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() armazena os valores inseridos, mas,
            // a variável '$cliente' original já foi atualizada
            $cliente = $form->getData();

            // ... executa uma ação, como salvar o cliente no BD
            // por exemplo, se Cliente é uma entity do Doctrine, então salve-a
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($cliente);
            $entityManager->flush();

            $this->addFlash('notice', 'Dados salvos com sucesso!');

            return $this->redirectToRoute('cliente_index');
        }

        return $this->renderForm('cliente/create.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route("/cliente/edit/{id}", name="cliente_edit")
     */
    public function edit(Request $request, $id){
        $cliente = $this->getDoctrine()->getRepository(Cliente::class)->find($id);

        $form = $this->createForm(ClienteType::class, $cliente);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() armazena os valores inseridos, mas,
            // a variável '$cliente' original já foi atualizada
            $cliente = $form->getData();

            // ... executa uma ação, como salvar o cliente no BD
            // por exemplo, se Cliente é uma entity do Doctrine, então salve-a
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($cliente);
            $entityManager->flush();

            $this->addFlash('notice', 'Dados atualizados com sucesso!');

            return $this->redirectToRoute('cliente_index');
        }

        return $this->renderForm('cliente/edit.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route("/cliente/delete{id}", name="cliente_delete")
     */
    public function delete($id){
        $cliente = $this->getDoctrine()->getRepository(Cliente::class)->find($id);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($cliente);
        $entityManager->flush();

        $this->addFlash('notice', 'Dados removidos com sucesso!');

        return $this->redirectToRoute('cliente_index');
    }
}

templates/cliente/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}CRUD Symfony - Novo Cliente{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <div class="d-flex justify-content-between w-100">
                        <h5>Criar (CRUD Symfony)</h5>
                        <a href="{{ url('cliente_index') }}" class="btn-info btn-sm">
                            <i class="fa fa-arrow-left"></i> Voltar
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    {{ form_start(form) }}
                        <div class="form-group">
                            {{ form_label(form.nome, "Nome do Cliente") }}
                            {{ form_widget(form.nome, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.cpf_cnpj, "CPF/CNPJ") }}
                            {{ form_widget(form.cpf_cnpj, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.telefone) }}
                            {{ form_widget(form.telefone, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            <button class="btn btn-info mt-2 text-white">Enviar</button>
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/cliente/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}CRUD Symfony - Editar Cliente{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <div class="d-flex justify-content-between w-100">
                        <h5>Editar (CRUD Symfony)</h5>
                        <a href="{{ url('cliente_index') }}" class="btn-info btn-sm">
                            <i class="fa fa-arrow-left"></i> Voltar
                        </a>
                    </div>
                </div>
                {% for message in app.flashes('notice') %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% endfor %}
                <div class="card-body">
                    {{ form_start(form) }}
                        <div class="form-group">
                            {{ form_label(form.nome, "Nome do Cliente") }}
                            {{ form_widget(form.nome, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.cpf_cnpj, "CPF/CNPJ") }}
                            {{ form_widget(form.cpf_cnpj, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.telefone) }}
                            {{ form_widget(form.telefone, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            <button class="btn btn-info mt-2 text-white">Atualizar</button>
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/cliente/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CRUD Symfony - Clientes{% endblock %}

{% block body %}
    {% for message in app.flashes('notice') %}
        <div class="alert alert-success mt-4 mb-b">
            {{ message }}
        </div>
    {% endfor %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header bg-dark text-white">
                        <div class="d-flex justify-content-between w-100">
                            <h5>Listagem de Clientes</h5>   <!-- criar uma tela -->
                            <a href="{{ url('cliente_create') }}" class="btn-primary btn-sm"> <!-- caminho do arquivo para esta tela, rota em web.php -> CargoController.php -> create; Laravel -->
                                <i class="fa fa-plus"></i> Novo Cliente  <!-- criar um botão -->
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nome</th>
                                    <th>CPF/CNPJ</th>
                                    <th>Telefone</th>
                                    <th colspan="4" class="text-center">Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for clientes in lista %}<!-- vem da function index no Controller -->
                                <tr>
                                    <th scope="row">{{ clientes.id }}</th>
                                    <td>{{ clientes.nome }}</td>
                                    <td>{{ clientes.cpfCnpj }}</td>
                                    <td>{{ clientes.telefone }} </td>
                                    <td class="text-center p-0 align-middle" width="70">
                                        <a class="btn btn-primary btn-sm" href="{{ path('cliente_edit', {'id': clientes.id }) }}">Editar</a>
                                    </td>
                                    <td class="text-center p-0 align-middle" width="70">
                                        <a class="btn btn-danger btn-sm" href="{{ path('cliente_delete', {'id':clientes.id }) }}">Excluir</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-center align-items-center">
            <div class="container">
                <a href="{{ url('home') }}" class="btn btn-outline-info btn-lg btn-block">Voltar</a>
            </div>
        </div>
    </div>
{% endblock %}