src/Entity/Produto.php
<?php

namespace App\Entity;

use App\Repository\ProdutoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProdutoRepository::class)
 */
class Produto
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $nome;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descricao;

    /**
     * @ORM\Column(type="float")
     */
    private $preco_unitario;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNome(): ?string
    {
        return $this->nome;
    }

    public function setNome(string $nome): self
    {
        $this->nome = $nome;

        return $this;
    }

    public function getDescricao(): ?string
    {
        return $this->descricao;
    }

    public function setDescricao(?string $descricao): self
    {
        $this->descricao = $descricao;

        return $this;
    }

    public function getPrecoUnitario(): ?float
    {
        return $this->preco_unitario;
    }

    public function setPrecoUnitario(float $preco_unitario): self
    {
        $this->preco_unitario = $preco_unitario;

        return $this;
    }
}

src/Form/ProdutoType.php
<?php

namespace App\Form;

use App\Entity\Produto;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProdutoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nome')
            ->add('descricao')
            ->add('preco_unitario')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produto::class,
        ]);
    }
}

src/Controller/ProdutoController.php
<?php

namespace App\Controller;

use App\Entity\Produto;
use App\Form\ProdutoType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ProdutoController extends AbstractController
{
    /**
     * @Route("/produto", name="produto_index")
     */
    public function index(): Response
    {
        $produtos = $this->getDoctrine()->getRepository(Produto::class)->findAll();

        return $this->render('produto/index.html.twig', [
            'lista' => $produtos
        ]);
    }

    /**
     * @Route("/produto/create", name="produto_create")
     */
    public function create(Request $request): Response
    {
        $produto = new Produto();

        $form = $this->createForm(ProdutoType::class, $produto);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() armazena os valores inseridos, mas,
            // a variável '$produto' original já foi atualizada
            $produto = $form->getData();

            // ... executa uma ação, como salvar o produto no BD
            // por exemplo, se Produto é uma entity do Doctrine, então salve-a
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($produto);
            $entityManager->flush();

            $this->addFlash('notice', 'Dados salvos com sucesso!');

            return $this->redirectToRoute('produto_index');
        }

        return $this->renderForm('produto/create.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route("/produto/edit/{id}", name="produto_edit")
     */
    public function edit(Request $request, $id){
        $produto = $this->getDoctrine()->getRepository(Produto::class)->find($id);

        $form = $this->createForm(ProdutoType::class, $produto);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() armazena os valores inseridos, mas,
            // a variável '$produto' original já foi atualizada
            $produto = $form->getData();

            // ... executa uma ação, como salvar o produto no BD
            // por exemplo, se Produto é uma entity do Doctrine, então salve-a
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($produto);
            $entityManager->flush();

            $this->addFlash('notice', 'Dados atualizados com sucesso!');

            return $this->redirectToRoute('produto_index');
        }

        return $this->renderForm('produto/edit.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route("/produto/delete{id}", name="produto_delete")
     */
    public function delete($id){
        $produto = $this->getDoctrine()->getRepository(Produto::class)->find($id);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($produto);
        $entityManager->flush();

        $this->addFlash('notice', 'Dados removidos com sucesso!');

        return $this->redirectToRoute('produto_index');
    }
}

templates/produto/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}CRUD Symfony - Novo Produto{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <div class="d-flex justify-content-between w-100">
                        <h5>Criar (CRUD Symfony)</h5>
                        <a href="{{ url('produto_index') }}" class="btn-info btn-sm">
                            <i class="fa fa-arrow-left"></i> Voltar
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    {{ form_start(form) }}
                        <div class="form-group">
                            {{ form_label(form.nome, "Nome do Produto") }}
                            {{ form_widget(form.nome, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.descricao, "Descrição") }}
                            {{ form_widget(form.descricao, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.preco_unitario, "Preço Unitário (R$)") }}
                            {{ form_widget(form.preco_unitario, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            <button class="btn btn-info mt-2 text-white">Enviar</button>
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/produto/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}CRUD Symfony - Editar Produto{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <div class="d-flex justify-content-between w-100">
                        <h5>Editar (CRUD Symfony)</h5>
                        <a href="{{ url('produto_index') }}" class="btn-info btn-sm">
                            <i class="fa fa-arrow-left"></i> Voltar
                        </a>
                    </div>
                </div>
                {% for message in app.flashes('notice') %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% endfor %}
                <div class="card-body">
                    {{ form_start(form) }}
                        <div class="form-group">
                            {{ form_label(form.nome, "Nome do Produto") }}
                            {{ form_widget(form.nome, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.descricao, "Descrição") }}
                            {{ form_widget(form.descricao, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.preco_unitario, "Preço Unitário (R$)") }}
                            {{ form_widget(form.preco_unitario, {'attr':{'class':'form-control'}})}}
                        </div>
                        <div class="form-group">
                            <button class="btn btn-info mt-2 text-white">Atualizar</button>
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/produto/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CRUD Symfony - Produtos{% endblock %}

{% block body %}
    {% for message in app.flashes('notice') %}
        <div class="alert alert-success mt-4 mb-b">
            {{ message }}
        </div>
    {% endfor %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header bg-dark text-white">
                        <div class="d-flex justify-content-between w-100">
                            <h5>Listagem de Produtos</h5>   <!-- criar uma tela -->
                            <a href="{{ url('produto_create') }}" class="btn-primary btn-sm"> <!-- caminho do arquivo para esta tela, rota em web.php -> CargoController.php -> create; Laravel -->
                                <i class="fa fa-plus"></i> Novo Produto  <!-- criar um botão -->
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <td>ID</td>
                                    <td>Nome</td>
                                    <td>Descrição</td>
                                    <td>Preço unitário (R$)</td>
                                    <td colspan="4" class="text-center">Ações</td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for produtos in lista %}<!-- vem da function index no Controller -->
                                <tr>
                                    <th scope="row">{{ produtos.id }}</th>
                                    <td>{{ produtos.nome }}</td>
                                    <td>{{ produtos.descricao }}</td>
                                    <td>R${{ produtos.precoUnitario }} </td>
                                    <td class="text-center p-0 align-middle" width="70">
                                        <a class="btn btn-primary btn-sm" href="{{ path('produto_edit', {'id': produtos.id }) }}">Editar</a>
                                    </td>
                                    <td class="text-center p-0 align-middle" width="70">
                                        <a class="btn btn-danger btn-sm" href="{{ path('produto_delete', {'id':produtos.id }) }}">Excluir</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-center align-items-center">
            <div class="container">
                <a href="{{ url('home') }}" class="btn btn-outline-info btn-lg btn-block">Voltar</a>
            </div>
        </div>
    </div>
{% endblock %}